<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-3AUMI0TH" failures="1" tests="3" name="cucumberOptions.TestNGTestRunner" time="104.830" errors="0" timestamp="2023-08-21T14:21:16 IST" skipped="0">
  <testcase classname="cucumberOptions.TestNGTestRunner" name="runScenario" time="35.290"/>
  <testcase classname="cucumberOptions.TestNGTestRunner" name="runScenario" time="34.359"/>
  <testcase classname="cucumberOptions.TestNGTestRunner" name="runScenario" time="35.181">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertFalse(Assert.java:79)
at org.testng.Assert.assertFalse(Assert.java:89)
at stepDefinitions.CheckoutPagestepdefinitions.verify_user_has_ability_to_apply_promocode_and_place_the_order(CheckoutPagestepdefinitions.java:46)
at âœ½.verify user has ability to apply promocode and place the order(file:///C:/Users/sujith%20k%20m/OneDrive/Documents/Automation/CucumberFramework/src/test/java/features/checkout.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- cucumberOptions.TestNGTestRunner -->
